# Generated by Django 3.0.8 on 2020-08-11 09:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='机柜编号')),
                ('position', models.CharField(max_length=80, verbose_name='机柜位置')),
                ('desc', models.TextField(blank=True, default='', verbose_name='备注信息')),
            ],
            options={
                'verbose_name': '机柜信息',
                'verbose_name_plural': '机柜信息',
            },
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, verbose_name='键')),
                ('value', models.CharField(max_length=80, verbose_name='值')),
                ('desc', models.CharField(blank=True, default='', max_length=100, verbose_name='备注')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='cmdb.Code')),
            ],
            options={
                'verbose_name': '字典',
                'verbose_name_plural': '字典',
            },
        ),
        migrations.CreateModel(
            name='ConnectionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('hostname', models.CharField(max_length=50, verbose_name='设备地址(IP或域名)')),
                ('port', models.IntegerField(default=22, verbose_name='SSH端口')),
                ('username', models.CharField(blank=True, default='', max_length=15, verbose_name='SSH用户名')),
                ('password', models.CharField(blank=True, default='', max_length=80, verbose_name='SSH密码')),
                ('private_key', models.CharField(blank=True, default='', max_length=100, verbose_name='密钥路径')),
                ('auth_type', models.CharField(choices=[('private_key', '密钥认证'), ('password', '密码认证')], default='', max_length=30)),
                ('status', models.CharField(blank=True, default='', max_length=10)),
            ],
            options={
                'verbose_name': 'SSH连接信息',
                'verbose_name_plural': 'SSH连接信息',
            },
        ),
        migrations.CreateModel(
            name='DeviceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('file_content', models.FileField(blank=True, null=True, upload_to='asset_file/%Y/%m', verbose_name='资产文件')),
                ('upload_user', models.CharField(max_length=20, verbose_name='上传人')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sys_hostname', models.CharField(blank=True, default='', max_length=150, verbose_name='主机名')),
                ('mac_address', models.CharField(blank=True, default='', max_length=150, verbose_name='MAC地址')),
                ('sn_number', models.CharField(blank=True, default='', max_length=150, verbose_name='SN号码')),
                ('os_type', models.CharField(blank=True, default='', max_length=150, verbose_name='系统类型')),
                ('device_type', models.CharField(blank=True, default='', max_length=150, verbose_name='设备类型')),
                ('cpu_type', models.CharField(blank=True, default='', max_length=150, verbose_name='CPU类型')),
                ('cpu_num', models.IntegerField(blank=True, default=0, verbose_name='CPU数量')),
                ('mem_total', models.CharField(blank=True, default='', max_length=150, verbose_name='内存')),
                ('hostname', models.CharField(max_length=50, verbose_name='设备地址(IP或域名)')),
                ('network_type', models.IntegerField(blank=True, null=True, verbose_name='网络类型')),
                ('service_type', models.IntegerField(blank=True, null=True, verbose_name='服务类型')),
                ('operation_type', models.IntegerField(blank=True, null=True, verbose_name='业务类型')),
                ('leader', models.IntegerField(blank=True, null=True, verbose_name='责任人')),
                ('dev_cabinet', models.IntegerField(blank=True, null=True, verbose_name='机柜信息')),
                ('dev_connection', models.IntegerField(blank=True, null=True, verbose_name='连接信息')),
                ('buyDate', models.DateField(default=datetime.datetime.now, verbose_name='购买日期')),
                ('warrantyDate', models.DateField(default=datetime.datetime.now, verbose_name='到保日期')),
                ('desc', models.TextField(blank=True, default='', verbose_name='备注信息')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='cmdb.DeviceInfo')),
            ],
            options={
                'verbose_name': '设备信息',
                'verbose_name_plural': '设备信息',
            },
        ),
        migrations.CreateModel(
            name='DeviceScanInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('hostname', models.CharField(max_length=50, verbose_name='设备地址(IP或域名)')),
                ('port', models.IntegerField(default=22, verbose_name='SSH端口')),
                ('username', models.CharField(blank=True, default='', max_length=15, verbose_name='SSH用户名')),
                ('password', models.CharField(blank=True, default='', max_length=80, verbose_name='SSH密码')),
                ('private_key', models.CharField(blank=True, default='', max_length=100, verbose_name='密钥路径')),
                ('auth_type', models.CharField(choices=[('private_key', '密钥认证'), ('password', '密码认证')], default='', max_length=30)),
                ('status', models.CharField(blank=True, default='', max_length=10)),
                ('sys_hostname', models.CharField(blank=True, default='', max_length=150, verbose_name='主机名')),
                ('mac_address', models.CharField(blank=True, default='', max_length=150, verbose_name='MAC地址')),
                ('sn_number', models.CharField(blank=True, default='', max_length=150, verbose_name='SN号码')),
                ('os_type', models.CharField(blank=True, default='', max_length=150, verbose_name='系统类型')),
                ('device_type', models.CharField(blank=True, default='', max_length=150, verbose_name='设备类型')),
                ('cpu_type', models.CharField(blank=True, default='', max_length=150, verbose_name='CPU类型')),
                ('cpu_num', models.IntegerField(blank=True, default=0, verbose_name='CPU数量')),
                ('mem_total', models.CharField(blank=True, default='', max_length=150, verbose_name='内存')),
                ('error_message', models.CharField(blank=True, default='', max_length=80, verbose_name='错误信息')),
            ],
            options={
                'verbose_name': '扫描信息',
                'verbose_name_plural': '扫描信息',
            },
        ),
        migrations.CreateModel(
            name='VMConnectionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('hostname', models.CharField(max_length=50, verbose_name='设备地址(IP或域名)')),
                ('port', models.IntegerField(default=22, verbose_name='SSH端口')),
                ('username', models.CharField(blank=True, default='', max_length=15, verbose_name='SSH用户名')),
                ('password', models.CharField(blank=True, default='', max_length=80, verbose_name='SSH密码')),
                ('status', models.CharField(blank=True, default='', max_length=10)),
            ],
            options={
                'verbose_name': 'SSH连接信息',
                'verbose_name_plural': 'SSH连接信息',
            },
        ),
        migrations.CreateModel(
            name='VMDeviceScanInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('hostname', models.CharField(max_length=50, verbose_name='设备地址(IP或域名)')),
                ('port', models.IntegerField(default=22, verbose_name='SSH端口')),
                ('username', models.CharField(blank=True, default='', max_length=15, verbose_name='SSH用户名')),
                ('password', models.CharField(blank=True, default='', max_length=80, verbose_name='SSH密码')),
                ('status', models.CharField(blank=True, default='', max_length=10)),
                ('sys_hostname', models.CharField(blank=True, default='', max_length=150, verbose_name='主机名')),
                ('mac_address', models.CharField(blank=True, default='', max_length=150, verbose_name='MAC地址')),
                ('sn_number', models.CharField(blank=True, default='', max_length=150, verbose_name='SN号码')),
                ('os_type', models.CharField(blank=True, default='', max_length=150, verbose_name='系统类型')),
                ('device_type', models.CharField(blank=True, default='', max_length=150, verbose_name='设备类型')),
                ('cpu_type', models.CharField(blank=True, default='', max_length=150, verbose_name='CPU类型')),
                ('cpu_num', models.IntegerField(blank=True, default=0, verbose_name='CPU数量')),
                ('mem_total', models.CharField(blank=True, default='', max_length=150, verbose_name='内存')),
                ('error_message', models.CharField(blank=True, default='', max_length=80, verbose_name='错误信息')),
            ],
            options={
                'verbose_name': '扫描信息',
                'verbose_name_plural': '扫描信息',
            },
        ),
        migrations.RemoveField(
            model_name='businessunit',
            name='parent_unit',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='asset',
        ),
        migrations.AlterUniqueTogether(
            name='disk',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='disk',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='eventlog',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='eventlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='networkdevice',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='networkdevice',
            name='firmware',
        ),
        migrations.RemoveField(
            model_name='newassetapprovalzone',
            name='approved_by',
        ),
        migrations.AlterUniqueTogether(
            name='nic',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='nic',
            name='asset',
        ),
        migrations.AlterUniqueTogether(
            name='raidadaptor',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='raidadaptor',
            name='asset',
        ),
        migrations.AlterUniqueTogether(
            name='ram',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ram',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='securitydevice',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='server',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='server',
            name='hosted_on',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='creator',
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='BusinessUnit',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='CPU',
        ),
        migrations.DeleteModel(
            name='Disk',
        ),
        migrations.DeleteModel(
            name='EventLog',
        ),
        migrations.DeleteModel(
            name='IDC',
        ),
        migrations.DeleteModel(
            name='Manufactory',
        ),
        migrations.DeleteModel(
            name='NetworkDevice',
        ),
        migrations.DeleteModel(
            name='NewAssetApprovalZone',
        ),
        migrations.DeleteModel(
            name='NIC',
        ),
        migrations.DeleteModel(
            name='RaidAdaptor',
        ),
        migrations.DeleteModel(
            name='RAM',
        ),
        migrations.DeleteModel(
            name='SecurityDevice',
        ),
        migrations.DeleteModel(
            name='Server',
        ),
        migrations.DeleteModel(
            name='Software',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='devicefile',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.DeviceInfo', verbose_name='设备'),
        ),
    ]
