# Generated by Django 3.0.8 on 2020-09-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20200909_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinfo',
            name='Manufacturercontact',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='厂商联系电话'),
        ),
        migrations.AddField(
            model_name='deviceinfo',
            name='Manufacturerleader',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='厂商责任人'),
        ),
    ]
